from models import db, PrepaidPackage, ServicePackage, Membership, StudentOffer, YearlyMembership, KittyParty, Service

def autogenerated_service_pkg_name(sp: "ServicePackage") -> str:
    """Generate a nice display name for service packages like 'Pay 3 Get 4 (+1 free)'"""
    try:
        pf = int(sp.pay_for or 0)
        total = int(sp.total_services or 0)
        free = max(total - pf, 0)
        base = f"Pay {pf} Get {total}" if pf and total else (sp.name or "Service Package")
        if free:
            base += f" (+{free} free)"
        return base
    except Exception:
        return sp.name or "Service Package"

def resolve_package_display_name(package_type: str, package_id: int) -> str:
    """Resolve a human-readable display name for any package type"""
    pt = (package_type or "").lower()
    
    if pt == "prepaid":
        p = db.session.get(PrepaidPackage, package_id)
        if not p:
            return "Prepaid Package"
        return p.name or f"Prepaid ₹{int(p.actual_price or 0):,} → ₹{int(p.after_value or 0):,}"
    
    if pt in ("service_package", "service"):
        sp = db.session.get(ServicePackage, package_id)
        if not sp:
            return "Service Package"
        return sp.name or autogenerated_service_pkg_name(sp)
    
    if pt == "membership":
        m = db.session.get(Membership, package_id)
        return (m.name if m else None) or "Membership"
    
    if pt == "student":
        s = db.session.get(StudentOffer, package_id)
        return (getattr(s, "name", None)) or "Student Offer"
    
    if pt in ("yearly", "yearly_membership"):
        y = db.session.get(YearlyMembership, package_id)
        return (y.name if y else None) or "Yearly Membership"
    
    if pt in ("kitty", "kitty_party"):
        k = db.session.get(KittyParty, package_id)
        return (k.name if k else None) or "Kitty Party"
    
    return "Package"

def resolve_service_name(service_id: int) -> str | None:
    """Resolve the service name from service ID"""
    if not service_id:
        return None
    s = db.session.get(Service, service_id)
    return s.name if s else None
